export const BINEK_MARKALAR = [
  'ALFA ROMEO', 'AUDI', 'BENTLEY', 'BMW', 'BYD', 'CHERY', 'CITROEN',
  'CUPRA', 'DACIA', 'DFSK', 'DS', 'FEST', 'FIAT', 'FORD', 'GAZ',
  'HONDA', 'HONGQI', 'HYUNDAI', 'ISUZU', 'JAGUAR', 'KIA', 'LAND ROVER',
  'LEAPMOTOR', 'LEXUS', 'MASERATI', 'MAXUS', 'MERCEDES', 'MG', 'MINI',
  'NIEVE', 'NISSAN', 'OPEL', 'PEUGEOT', 'PORSCHE', 'RENAULT',
  'RENAULT (OYAK)', 'SEAT', 'SERES', 'SKODA', 'SKYWELL', 'SSANGYONG',
  'SUBARU', 'SUZUKI', 'TESLA', 'TOGG', 'TOYOTA', 'VOLKSWAGEN', 'VOLVO',
  'VOYAH',
];
